In [224]:
import pandas as pd
import numpy as np

crimen = pd.read_csv("../Consultas/cubo_crimen_Alcaldias.csv")
aire = pd.read_csv("../Consultas/cubo_aire_Alcaldias.csv")

In [225]:
df_crimen = pd.DataFrame(crimen)
df_aire = pd.DataFrame(aire)

In [226]:
df_crimen

       Dia  Mes  Anio               Alcaldia  countCrimenes
0        1    1  2016         ALVARO OBREGON             10
1        1    1  2016           AZCAPOTZALCO              7
2        1    1  2016          BENITO JUAREZ              7
3        1    1  2016               COYOACAN             12
4        1    1  2016  CUAJIMALPA DE MORELOS             10
...    ...  ...   ...                    ...            ...
27949   31   12  2020         MIGUEL HIDALGO              3
27950   31   12  2020                TLAHUAC              3
27951   31   12  2020                TLALPAN              4
27952   31   12  2020    VENUSTIANO CARRANZA             14
27953   31   12  2020             XOCHIMILCO              1

[27954 rows x 5 columns]

In [227]:
df_aire

       Dia  Mes  Anio               Alcaldia    Latitud   Longitud  avgAQI
0        1    1  2016           AZCAPOTZALCO  19.468405 -99.169792     206
1        1    1  2016          BENITO JUAREZ  19.370464 -99.159599     184
2        1    1  2016  CUAJIMALPA DE MORELOS  19.365313 -99.291702     164
3        1    1  2016             CUAUHTEMOC  19.411617 -99.152206     178
4        1    1  2016              IZTACALCO  19.384413 -99.117638     187
...    ...  ...   ...                    ...        ...        ...     ...
16853   31   12  2020          BENITO JUAREZ  19.370464 -99.159599     117
16854   31   12  2020  CUAJIMALPA DE MORELOS  19.357357 -99.262863      97
16855   31   12  2020       GUSTAVO A MADERO  19.482700 -99.094521     128
16856   31   12  2020             IZTAPALAPA  19.360794 -99.073883     127
16857   31   12  2020    VENUSTIANO CARRANZA  19.424610 -99.119591     127

[16858 rows x 7 columns]

In [65]:
occur = df_crimen_mod.groupby(['Alcaldia']).size()
occur

Alcaldia
ALVARO OBREGON           1827
AZCAPOTZALCO             1818
BENITO JUAREZ            1806
CUAJIMALPA DE MORELOS    1393
CUAUHTEMOC               1827
GUSTAVO A MADERO         1827
IZTACALCO                1822
IZTAPALAPA               1827
MIGUEL HIDALGO           1813
MILPA ALTA               1255
TLAHUAC                  1778
TLALPAN                  1823
VENUSTIANO CARRANZA      1826
dtype: int64

In [122]:
occur_a = df_aire.groupby(['Alcaldia']).size()
occur_a

Alcaldia
ALVARO OBREGON            682
AZCAPOTZALCO             1302
BENITO JUAREZ            1570
CUAJIMALPA DE MORELOS    2796
CUAUHTEMOC               1286
GUSTAVO A MADERO          520
IZTACALCO                1546
IZTAPALAPA               1057
MIGUEL HIDALGO           1197
MILPA ALTA                608
TLAHUAC                  1370
TLALPAN                  1381
VENUSTIANO CARRANZA      1543
dtype: int64

In [228]:
id_list = []

for i in range(len(df_aire)):
    id_new = str(df_aire['Dia'][i]) + '_' + str(df_aire['Mes'][i]) + '_' + str(df_aire['Anio'][i]) + '_' + df_aire['Alcaldia'][i][0:5]
    id_list.append(id_new)

df_aire['ID'] = id_list
df_aire

,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI,ID
0,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,206,1_1_2016_AZCAP
1,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,184,1_1_2016_BENIT
2,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,164,1_1_2016_CUAJI
3,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,178,1_1_2016_CUAUH
4,1,1,2016,IZTACALCO,19.384413,-99.117638,187,1_1_2016_IZTAC
...,...,...,...,...,...,...,...,...
16853,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117,31_12_2020_BENIT
16854,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97,31_12_2020_CUAJI
16855,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128,31_12_2020_GUSTA
16856,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127,31_12_2020_IZTAP
16857,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127,31_12_2020_VENUS

In [229]:
id_list_crimen = []

for i in range(len(df_crimen)):
    id_new_crimen = str(df_crimen['Dia'][i]) + '_' + str(df_crimen['Mes'][i]) + '_' + str(df_crimen['Anio'][i]) + '_' + df_crimen['Alcaldia'][i][0:5]
    id_list_crimen.append(id_new_crimen)

df_crimen['ID'] = id_list_crimen
df_crimen

       Dia  Mes  Anio               Alcaldia  countCrimenes                ID
0        1    1  2016         ALVARO OBREGON             10    1_1_2016_ALVAR
1        1    1  2016           AZCAPOTZALCO              7    1_1_2016_AZCAP
2        1    1  2016          BENITO JUAREZ              7    1_1_2016_BENIT
3        1    1  2016               COYOACAN             12    1_1_2016_COYOA
4        1    1  2016  CUAJIMALPA DE MORELOS             10    1_1_2016_CUAJI
...    ...  ...   ...                    ...            ...               ...
27949   31   12  2020         MIGUEL HIDALGO              3  31_12_2020_MIGUE
27950   31   12  2020                TLAHUAC              3  31_12_2020_TLAHU
27951   31   12  2020                TLALPAN              4  31_12_2020_TLALP
27952   31   12  2020    VENUSTIANO CARRANZA             14  31_12_2020_VENUS
27953   31   12  2020             XOCHIMILCO              1  31_12_2020_XOCHI

[27954 rows x 6 columns]

In [79]:
if df_aire['ID'][0] in df_crimen_mod['ID'].tolist():
    print(df_aire['ID'][0])
else: print('nada')

112016AZCAP

In [230]:
df_cimen_1 = df_crimen[df_crimen['ID'].isin(df_aire['ID'].tolist())]
df_cimen_1

       Dia  Mes  Anio               Alcaldia  countCrimenes                ID
1        1    1  2016           AZCAPOTZALCO              7    1_1_2016_AZCAP
2        1    1  2016          BENITO JUAREZ              7    1_1_2016_BENIT
4        1    1  2016  CUAJIMALPA DE MORELOS             10    1_1_2016_CUAJI
5        1    1  2016             CUAUHTEMOC             12    1_1_2016_CUAUH
7        1    1  2016              IZTACALCO             12    1_1_2016_IZTAC
...    ...  ...   ...                    ...            ...               ...
27941   31   12  2020          BENITO JUAREZ              2  31_12_2020_BENIT
27943   31   12  2020  CUAJIMALPA DE MORELOS              2  31_12_2020_CUAJI
27945   31   12  2020       GUSTAVO A MADERO             24  31_12_2020_GUSTA
27947   31   12  2020             IZTAPALAPA             15  31_12_2020_IZTAP
27952   31   12  2020    VENUSTIANO CARRANZA             14  31_12_2020_VENUS

[15081 rows x 6 columns]

In [231]:
df_aire_1 = df_aire[df_aire['ID'].isin(df_crimen['ID'].tolist())]
df_aire_1

,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI,ID
0,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,206,1_1_2016_AZCAP
1,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,184,1_1_2016_BENIT
2,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,164,1_1_2016_CUAJI
3,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,178,1_1_2016_CUAUH
4,1,1,2016,IZTACALCO,19.384413,-99.117638,187,1_1_2016_IZTAC
...,...,...,...,...,...,...,...,...
16853,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117,31_12_2020_BENIT
16854,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97,31_12_2020_CUAJI
16855,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128,31_12_2020_GUSTA
16856,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127,31_12_2020_IZTAP
16857,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127,31_12_2020_VENUS

In [232]:
print(len(df_aire_1))
print(len(df_cimen_1))

15865
15081

In [233]:
df_aire_2 = df_aire_1.drop_duplicates(subset=['ID'])

In [234]:
df_aire_2

,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI,ID
0,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,206,1_1_2016_AZCAP
1,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,184,1_1_2016_BENIT
2,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,164,1_1_2016_CUAJI
3,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,178,1_1_2016_CUAUH
4,1,1,2016,IZTACALCO,19.384413,-99.117638,187,1_1_2016_IZTAC
...,...,...,...,...,...,...,...,...
16853,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117,31_12_2020_BENIT
16854,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97,31_12_2020_CUAJI
16855,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128,31_12_2020_GUSTA
16856,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127,31_12_2020_IZTAP
16857,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127,31_12_2020_VENUS

In [235]:
df_cimen_2 = df_cimen_1.drop_duplicates(subset=['ID'])
df_cimen_2

       Dia  Mes  Anio               Alcaldia  countCrimenes                ID
1        1    1  2016           AZCAPOTZALCO              7    1_1_2016_AZCAP
2        1    1  2016          BENITO JUAREZ              7    1_1_2016_BENIT
4        1    1  2016  CUAJIMALPA DE MORELOS             10    1_1_2016_CUAJI
5        1    1  2016             CUAUHTEMOC             12    1_1_2016_CUAUH
7        1    1  2016              IZTACALCO             12    1_1_2016_IZTAC
...    ...  ...   ...                    ...            ...               ...
27941   31   12  2020          BENITO JUAREZ              2  31_12_2020_BENIT
27943   31   12  2020  CUAJIMALPA DE MORELOS              2  31_12_2020_CUAJI
27945   31   12  2020       GUSTAVO A MADERO             24  31_12_2020_GUSTA
27947   31   12  2020             IZTAPALAPA             15  31_12_2020_IZTAP
27952   31   12  2020    VENUSTIANO CARRANZA             14  31_12_2020_VENUS

[15081 rows x 6 columns]

In [236]:
df_cimen_2['Latitud'] = 0
df_cimen_2['Longitud'] = 0

In [237]:
occur_a = df_cimen_2.groupby(['Alcaldia']).size()
occur_a.index.to_list()[12]

'VENUSTIANO CARRANZA'

In [238]:
df_aire_2['Latitud'].loc[(df_aire_2['Alcaldia'] == 'AZCAPOTZALCO')].values[1]

19.4684047698975

In [239]:
for i in range(len(occur_a.index.to_list())):
    df_cimen_2['Latitud'].loc[(df_cimen_2['Alcaldia'] == occur_a.index.to_list()[i])] = df_aire_2['Latitud'].loc[(df_aire_2['Alcaldia'] == occur_a.index.to_list()[i])].values[1]
    df_cimen_2['Longitud'].loc[(df_cimen_2['Alcaldia'] == occur_a.index.to_list()[i])] = df_aire_2['Longitud'].loc[(df_aire_2['Alcaldia'] == occur_a.index.to_list()[i])].values[1]

df_cimen_2

C:\Users\dgonz\AppData\Local\Temp\ipykernel_14040\3265668260.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cimen_2['Latitud'].loc[(df_cimen_2['Alcaldia'] == occur_a.index.to_list()[i])] = df_aire_2['Latitud'].loc[(df_aire_2['Alcaldia'] == occur_a.index.to_list()[i])].values[1]
C:\Users\dgonz\AppData\Local\Temp\ipykernel_14040\3265668260.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cimen_2['Longitud'].loc[(df_cimen_2['Alcaldia'] == occur_a.index.to_list()[i])] = df_aire_2['Longitud'].loc[(df_aire_2['Alcaldia'] == occur_a.index.to_list()[i])].values[1]

,Dia,Mes,Anio,Alcaldia,countCrimenes,ID,Latitud,Longitud
1,1,1,2016,AZCAPOTZALCO,7,1_1_2016_AZCAP,19.468405,-99.169792
2,1,1,2016,BENITO JUAREZ,7,1_1_2016_BENIT,19.370464,-99.159599
4,1,1,2016,CUAJIMALPA DE MORELOS,10,1_1_2016_CUAJI,19.365313,-99.291702
5,1,1,2016,CUAUHTEMOC,12,1_1_2016_CUAUH,19.411617,-99.152206
7,1,1,2016,IZTACALCO,12,1_1_2016_IZTAC,19.384413,-99.117638
...,...,...,...,...,...,...,...,...
27941,31,12,2020,BENITO JUAREZ,2,31_12_2020_BENIT,19.370464,-99.159599
27943,31,12,2020,CUAJIMALPA DE MORELOS,2,31_12_2020_CUAJI,19.365313,-99.291702
27945,31,12,2020,GUSTAVO A MADERO,24,31_12_2020_GUSTA,19.482700,-99.094521
27947,31,12,2020,IZTAPALAPA,15,31_12_2020_IZTAP,19.360794,-99.073883
27952,31,12,2020,VENUSTIANO CARRANZA,14,31_12_2020_VENUS,19.424610,-99.119591

In [240]:
df_aire_3 = df_aire_2[['ID', 'Dia', 'Mes', 'Anio', 'Alcaldia', 'Latitud', 'Longitud', 'avgAQI']]
df_aire_3

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI
0,1_1_2016_AZCAP,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,206
1,1_1_2016_BENIT,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,184
2,1_1_2016_CUAJI,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,164
3,1_1_2016_CUAUH,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,178
4,1_1_2016_IZTAC,1,1,2016,IZTACALCO,19.384413,-99.117638,187
...,...,...,...,...,...,...,...,...
16853,31_12_2020_BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117
16854,31_12_2020_CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97
16855,31_12_2020_GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128
16856,31_12_2020_IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127
16857,31_12_2020_VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127

In [241]:
df_cimen_3 = df_cimen_2[['ID', 'Dia', 'Mes', 'Anio', 'Alcaldia', 'Latitud', 'Longitud', 'countCrimenes']]
df_cimen_3

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,countCrimenes
1,1_1_2016_AZCAP,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,7
2,1_1_2016_BENIT,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,7
4,1_1_2016_CUAJI,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,10
5,1_1_2016_CUAUH,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,12
7,1_1_2016_IZTAC,1,1,2016,IZTACALCO,19.384413,-99.117638,12
...,...,...,...,...,...,...,...,...
27941,31_12_2020_BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,2
27943,31_12_2020_CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.365313,-99.291702,2
27945,31_12_2020_GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,24
27947,31_12_2020_IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,15
27952,31_12_2020_VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,14

In [242]:
df_cimen_3.reset_index(drop=True)
df_aire_3.reset_index(drop=True)

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI
0,1_1_2016_AZCAP,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,206
1,1_1_2016_BENIT,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,184
2,1_1_2016_CUAJI,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,164
3,1_1_2016_CUAUH,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,178
4,1_1_2016_IZTAC,1,1,2016,IZTACALCO,19.384413,-99.117638,187
...,...,...,...,...,...,...,...,...
15076,31_12_2020_BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117
15077,31_12_2020_CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97
15078,31_12_2020_GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128
15079,31_12_2020_IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127
15080,31_12_2020_VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127

In [244]:
from pathlib import Path  
filepath = Path('../CSV_limpios/aire.csv')  

filepath.parent.mkdir(parents=True, exist_ok=True)  

df_aire_3.to_csv(filepath)

In [245]:
import pandas as pd
import numpy as np

crimen = pd.read_csv("../CSV_limpios/crimen.csv")
aire = pd.read_csv("../CSV_limpios/aire.csv")

In [246]:
df_crimen = pd.DataFrame(crimen)
df_aire = pd.DataFrame(aire)

In [247]:
df_aire = df_aire.drop(df_aire.columns[0], axis=1)
df_crimen = df_crimen.drop(df_crimen.columns[0], axis=1)

In [255]:
df_crimen.iloc[15070:]

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,countCrimenes
15070,30_12_2020_BENIT,30,12,2020,BENITO JUAREZ,19.370464,-99.159599,10
15071,30_12_2020_GUSTA,30,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,12
15072,30_12_2020_IZTAP,30,12,2020,IZTAPALAPA,19.360794,-99.073883,19
15073,30_12_2020_TLAHU,30,12,2020,TLAHUAC,19.246458,-99.010567,8
15074,30_12_2020_VENUS,30,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,12
15075,31_12_2020_ALVAR,31,12,2020,ALVARO OBREGON,19.325146,-99.204140,7
15076,31_12_2020_BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,2
15077,31_12_2020_CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.365313,-99.291702,2
15078,31_12_2020_GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,24
15079,31_12_2020_IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,15
15080,31_12_2020_VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,14

In [254]:
df_aire.iloc[15070:]

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI
15070,30_12_2020_BENIT,30,12,2020,BENITO JUAREZ,19.370464,-99.159599,112
15071,30_12_2020_GUSTA,30,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,142
15072,30_12_2020_IZTAP,30,12,2020,IZTAPALAPA,19.360794,-99.073883,137
15073,30_12_2020_TLAHU,30,12,2020,TLAHUAC,19.246458,-99.010567,138
15074,30_12_2020_VENUS,30,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,143
15075,31_12_2020_ALVAR,31,12,2020,ALVARO OBREGON,19.325146,-99.204140,118
15076,31_12_2020_BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117
15077,31_12_2020_CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97
15078,31_12_2020_GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128
15079,31_12_2020_IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127
15080,31_12_2020_VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127

In [256]:
occur = df_aire.groupby(['Alcaldia']).size()
occur

Alcaldia
ALVARO OBREGON            682
AZCAPOTZALCO             1294
BENITO JUAREZ            1549
CUAJIMALPA DE MORELOS    1366
CUAUHTEMOC               1286
GUSTAVO A MADERO          520
IZTACALCO                1541
IZTAPALAPA               1057
MIGUEL HIDALGO           1183
MILPA ALTA                358
TLAHUAC                  1326
TLALPAN                  1377
VENUSTIANO CARRANZA      1542
dtype: int64

In [257]:
occur_1 = df_crimen.groupby(['Alcaldia']).size()
occur_1

Alcaldia
ALVARO OBREGON            682
AZCAPOTZALCO             1294
BENITO JUAREZ            1549
CUAJIMALPA DE MORELOS    1366
CUAUHTEMOC               1286
GUSTAVO A MADERO          520
IZTACALCO                1541
IZTAPALAPA               1057
MIGUEL HIDALGO           1183
MILPA ALTA                358
TLAHUAC                  1326
TLALPAN                  1377
VENUSTIANO CARRANZA      1542
dtype: int64

In [258]:
df_aire.loc[(df_aire['Alcaldia'] == 'ALVARO OBREGON')]

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI
9315,17_1_2019_ALVAR,17,1,2019,ALVARO OBREGON,19.325146,-99.20414,144
9325,18_1_2019_ALVAR,18,1,2019,ALVARO OBREGON,19.325146,-99.20414,110
9334,19_1_2019_ALVAR,19,1,2019,ALVARO OBREGON,19.325146,-99.20414,105
9343,20_1_2019_ALVAR,20,1,2019,ALVARO OBREGON,19.325146,-99.20414,106
9350,21_1_2019_ALVAR,21,1,2019,ALVARO OBREGON,19.325146,-99.20414,109
...,...,...,...,...,...,...,...,...
15048,27_12_2020_ALVAR,27,12,2020,ALVARO OBREGON,19.325146,-99.20414,78
15055,28_12_2020_ALVAR,28,12,2020,ALVARO OBREGON,19.325146,-99.20414,86
15062,29_12_2020_ALVAR,29,12,2020,ALVARO OBREGON,19.325146,-99.20414,112
15069,30_12_2020_ALVAR,30,12,2020,ALVARO OBREGON,19.325146,-99.20414,96
15075,31_12_2020_ALVAR,31,12,2020,ALVARO OBREGON,19.325146,-99.20414,118

In [259]:
df_crimen.loc[(df_crimen['Alcaldia'] == 'ALVARO OBREGON')]

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,countCrimenes
9315,17_1_2019_ALVAR,17,1,2019,ALVARO OBREGON,19.325146,-99.20414,24
9325,18_1_2019_ALVAR,18,1,2019,ALVARO OBREGON,19.325146,-99.20414,24
9334,19_1_2019_ALVAR,19,1,2019,ALVARO OBREGON,19.325146,-99.20414,28
9343,20_1_2019_ALVAR,20,1,2019,ALVARO OBREGON,19.325146,-99.20414,20
9350,21_1_2019_ALVAR,21,1,2019,ALVARO OBREGON,19.325146,-99.20414,12
...,...,...,...,...,...,...,...,...
15048,27_12_2020_ALVAR,27,12,2020,ALVARO OBREGON,19.325146,-99.20414,10
15055,28_12_2020_ALVAR,28,12,2020,ALVARO OBREGON,19.325146,-99.20414,12
15062,29_12_2020_ALVAR,29,12,2020,ALVARO OBREGON,19.325146,-99.20414,7
15069,30_12_2020_ALVAR,30,12,2020,ALVARO OBREGON,19.325146,-99.20414,11
15075,31_12_2020_ALVAR,31,12,2020,ALVARO OBREGON,19.325146,-99.20414,7

In [223]:
df_aire_1.loc[(df_aire['ID'] == '1112019ALVAR')]

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI
11884,1112019ALVAR,1,11,2019,ALVARO OBREGON,19.325146,-99.20414,92

In [219]:
df_aire_1 = df_aire.sort_values(by=['Anio', 'Mes', 'Dia', 'Alcaldia'])
df_aire_1

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,avgAQI
0,112016AZCAP,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,206
1,112016BENIT,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,184
2,112016CUAJI,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,164
3,112016CUAUH,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,178
4,112016IZTAC,1,1,2016,IZTACALCO,19.384413,-99.117638,187
...,...,...,...,...,...,...,...,...
14915,31122020BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,117
14916,31122020CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.357357,-99.262863,97
14917,31122020GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,128
14918,31122020IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,127
14919,31122020VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,127

In [220]:
df_crimen_1 = df_crimen.sort_values(by=['Anio', 'Mes', 'Dia', 'Alcaldia'])
df_crimen_1

,ID,Dia,Mes,Anio,Alcaldia,Latitud,Longitud,countCrimenes
0,112016AZCAP,1,1,2016,AZCAPOTZALCO,19.468405,-99.169792,7
1,112016BENIT,1,1,2016,BENITO JUAREZ,19.370464,-99.159599,7
2,112016CUAJI,1,1,2016,CUAJIMALPA DE MORELOS,19.365313,-99.291702,10
3,112016CUAUH,1,1,2016,CUAUHTEMOC,19.411617,-99.152206,12
4,112016IZTAC,1,1,2016,IZTACALCO,19.384413,-99.117638,12
...,...,...,...,...,...,...,...,...
14915,31122020BENIT,31,12,2020,BENITO JUAREZ,19.370464,-99.159599,2
14916,31122020CUAJI,31,12,2020,CUAJIMALPA DE MORELOS,19.365313,-99.291702,2
14917,31122020GUSTA,31,12,2020,GUSTAVO A MADERO,19.482700,-99.094521,24
14918,31122020IZTAP,31,12,2020,IZTAPALAPA,19.360794,-99.073883,15
14919,31122020VENUS,31,12,2020,VENUSTIANO CARRANZA,19.424610,-99.119591,14