In [1]:
from geopy.geocoders import Nominatim
import time
import math

import seaborn as sns
import matplotlib.pyplot as plt

import savefig
import pandas as pd
import numpy as np

In [2]:
geo = Nominatim(user_agent="MyApp")

In [3]:
aire = pd.read_csv("E:\\7mo\\TT1\\Datos_aire\\Contaminantes\\csv_modificados\\aire_2011_2020_v2.csv")

In [4]:
df_aire = pd.DataFrame(aire)

In [6]:
df_aire = df_aire.drop(df_aire.columns[0], axis=1)

In [8]:
df_aire_100 = df_aire.head(100)

In [10]:
cat_estacion = pd.read_csv("E:\\7mo\\TT1\\Datos_aire\\Contaminantes\\csv\\cat_estacion.csv")
df_estacion = pd.DataFrame(cat_estacion)

In [11]:
df_aire_v2 = pd.DataFrame(columns=['Dia', 'Mes', 'Anio', 'Hora', 'Particula', 'Valor', 'Lugar', 'Estado', 'Latitud', 'Longitud'])

In [12]:
df_estacion

,cve_estac,nom_estac,longitud,latitud,alt,obs_estac,id_station
0,ACO,Acolman,-98.912003,19.635501,2198.0,NaN,484150020109
1,AJU,Ajusco,-99.162611,19.154286,2942.0,NaN,484090120400
2,AJM,Ajusco Medio,-99.207744,19.272161,2548.0,NaN,484090120609
3,ARA,Aragon,-99.074549,19.470218,2200.0,Finalizo operacion en 2010,484090050301
4,ATI,Atizapan,-99.254133,19.576963,2341.0,NaN,484150130101
...,...,...,...,...,...,...,...
64,VIF,Villa de las Flores,-99.096590,19.658223,2242.0,NaN,484150200109
65,XAL,Xalostoc,-99.082400,19.525995,2160.0,NaN,484150330415
66,XCH,Xochimilco,-99.118252,19.267066,2243.0,Finalizo operacion en 1999,484090130102
67,FAR,FES Aragon,-99.046176,19.473692,2230.0,NaN,484800150584
68,SAC,Santiago Acahualtepec,-99.009381,19.345610,2293.0,NaN,484800090073

In [54]:
estado = {}
latitud = {}
longitud = {}
for i in range(len(df_estacion)):
    latitud[df_estacion["nom_estac"][i]] = df_estacion["latitud"][i]
    longitud[df_estacion["nom_estac"][i]] = df_estacion["longitud"][i]
    address = geo.reverse(str(df_estacion["latitud"][i]) + ", " + str(df_estacion["longitud"][i]))
    #print(address, address.latitude, address.longitude)
    #x = str(address).split(", ")
    Estado_1 = ""
    if "Ciudad de México" in str(address):
        Estado_1 = "Ciudad de México"
        #print(Estado)
    else:
        Estado_1 = "Estado de México"
    estado[df_estacion["nom_estac"][i]] = Estado_1

In [56]:
estado_toAdd = []
latitud_toAdd = []
longitud_toAdd = []
#estado[df_aire_100['Lugar'][0]]
for i in range(len(df_aire)):
    estado_toAdd.append(estado[df_aire['Lugar'][i]])
    latitud_toAdd.append(latitud[df_aire['Lugar'][i]])
    longitud_toAdd.append(longitud[df_aire['Lugar'][i]])

In [57]:
df_aire['Estado'] = estado_toAdd
df_aire['Latitud'] = latitud_toAdd
df_aire['Longitud'] = longitud_toAdd
#df.insert(2, "Age", [21, 23, 24, 21], True)

In [60]:
from pathlib import Path  
filepath = Path('E:\\7mo\\TT1\\Datos_aire\\Contaminantes\\csv_modificados\\aire_2011_2020_v3.csv')  

filepath.parent.mkdir(parents=True, exist_ok=True)  

df_aire.to_csv(filepath)

In [63]:
# choose a random element from a list
from random import seed
from random import choice
# seed random number generator
seed(1)

test_1 = []
for i in range(10):
    test_1.append((i+1)/10)

print(test_1)
# make choices from the sequence
for _ in range(5):
    selection = choice(test_1)
    print(selection)

[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
0.3
1.0
0.2
0.5
0.2

In [64]:
test_2 = []
#estado[df_aire_100['Lugar'][0]]
for i in range(len(df_aire)):
    test_2.append(choice(test_1))

In [65]:
df_aire['test_map'] = test_2

In [67]:
import folium
from folium.plugins import HeatMap

In [68]:
mapObj = folium.Map(location=[19.417239, -99.147519], zoom_start=12)

In [69]:
colrGradient = {0.0: '#FAEADC',
                0.2: '#F6B48F',
                0.4: '#F37651',
                0.6: '#E13342',
                0.7: '#AD1759',
                0.8: '#701F57',
                1.0: '#35193E'}

In [70]:
df_aire

,Dia,Mes,Anio,Hora,Lugar,Particula,Valor,Estado,Latitud,Longitud,test_map
0,1,1,2011,1.0,Acolman,CO,-99.0,Estado de México,19.635501,-98.912003,0.8
1,1,1,2011,1.0,Camarones,CO,-99.0,Ciudad de México,19.468404,-99.169794,0.8
2,1,1,2011,1.0,Chalco,CO,-99.0,Estado de México,19.266948,-98.886088,0.8
3,1,1,2011,1.0,Cuajimalpa,CO,-99.0,Ciudad de México,19.365313,-99.291705,0.7
4,1,1,2011,1.0,FES Acatlan,CO,1.4,Estado de México,19.482473,-99.243524,0.4
...,...,...,...,...,...,...,...,...,...,...,...
6489022,31,12,2020,23.0,Tlalnepantla,PM2.5,33.0,Estado de México,19.529077,-99.204597,0.3
6489023,31,12,2020,23.0,Tultitlan,PM2.5,-99.0,Estado de México,19.602542,-99.177173,1.0
6489024,31,12,2020,23.0,UAM Iztapalapa,PM2.5,42.0,Ciudad de México,19.360794,-99.073880,0.8
6489025,31,12,2020,23.0,Villa de las Flores,PM2.5,178.0,Estado de México,19.658223,-99.096590,0.4
6489026,31,12,2020,23.0,Xalostoc,PM2.5,-99.0,Estado de México,19.525995,-99.082400,0.4

In [72]:
data = []
for i in range(len(df_aire)):
    data_1 = []
    data_1.append(df_aire['Latitud'][i])
    data_1.append(df_aire['Longitud'][i])
    data_1.append(df_aire['test_map'][i])
    #coord_list[].append()
    data.append(data_1)

In [73]:
HeatMap(data, gradient=colrGradient).add_to(mapObj)

In [74]:
mapObj.save('output.html')

In [81]:
df_aire.loc[(df_aire['Particula'] == "CO") & (df_aire['Lugar'] == "UAM Iztapalapa")]['test_map'].mean()

0.5508825305666707